language: cpp
sudo: required
matrix:
    include:
        - os: linux
          env:
            - BUILDING_FOR_OS=linux
            - CMAKE_BUILD_FLAGS="-DCOVERAGE=ON"
            - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
          addons:
              apt:
                  packages:
                      - g++-7
                      - valgrind
                      - gawk
                      - sed
                      - shtool
                      - libboost-all-dev
                      - libffi-dev
                      - libssl-dev
                      - libprocps4-dev
                      - libgmp3-dev
                      - flex
                      - bison
                  sources: &sources
                      - ubuntu-toolchain-r-test
          before_script:
              - echo "========================================= before_script (coverage)"
              - sudo apt-get update -qq
              - sudo python -m pip install --upgrade pip
              - sudo python -m pip install pyopenssl ndg-httpsclient pyasn1
              - sudo python -m pip install requests[security]
              - sudo python -m pip install codecov --ignore-installed
              - echo "========================================= before_script (codecov installed)"
              - mkdir -p build
              - cd build
              - cd ..
          after_success:
              - cd build
              - echo "========================================= after_success (coverage)"
              - ./bls_unit_test || travis_terminate 1
              - ./dkg_unit_test || travis_terminate 1
              - ./bls_test || travis_terminate 1
              - ./threshold_encryption/te_unit_test || travis_terminate 1
              - ./threshold_encryption/te_test || travis_terminate 1
              - ./threshold_encryption/dkg_te_unit_test || travis_terminate 1
              - cd ..
              - ./get_code_cov
              - echo "========================================= after_success (coverage gathered to gcov files)"
              - codecov
              - bash <(curl -s https://codecov.io/bash)
              - echo "========================================= after_success (coverage end)"
        - os: linux
          env:
            - BUILDING_FOR_OS=linux
            - CMAKE_BUILD_FLAGS=""
            - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
          addons:
              apt:
                  packages:
                      - g++-7
                      - valgrind
                      - gawk
                      - sed
                      - lcov
                      - shtool
                      - libboost-all-dev
                      - libprocps4-dev
                      - libgmp3-dev
                  sources: &sources
                      - ubuntu-toolchain-r-test
        - os: linux
          env:
            - PYTHON=3.6
            - BUILDING_FOR_OS=linux
            - CMAKE_BUILD_FLAGS="-DBUILD_WITH_FPIC=ON"
            - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
          addons:
              apt:
                  packages:
                      - g++-7
                      - valgrind
                      - gawk
                      - sed
                      - lcov
                      - shtool
                      - libboost-all-dev
                      - libprocps4-dev
                      - libgmp3-dev
                      - python3.6
                      - python3.6-dev
                  sources: &sources
                      - deadsnakes
                      - ubuntu-toolchain-r-test
          after_success:
              - cd python
              - echo "========================================= after_success (dkg)"
              - ./setup.sh || travis terminate 1
              - ./test.sh || travis terminate 1
              - cd ..
        - os: osx
          osx_image: xcode10.1
          env:
            - BUILDING_FOR_OS=osx
            - CMAKE_BUILD_FLAGS="-DWITH_PROCPS=OFF"
            - OPENSSL_ROOT_DIR=/usr/local/opt/openssl
            - LIBTOOL=glibtool
          addons:
              apt:
                  packages:
                      - boost
                      - shtool
                      - libtool
          before_script:
              - ln -s $(which glibtool) /usr/local/bin/libtool || true
              - ln -s $(which glibtoolize) /usr/local/bin/libtoolize || true
before_install:
    - sudo apt-get update
    - sudo apt-get install python3.6
    - sudo apt-get install python3-pip
    - pip3 install --upgrade pip
    - eval "${MATRIX_EVAL}"
script:
    - pip3 install coincurve
    - echo "========================================= script (1)"
    - echo "CMAKE_BUILD_FLAGS=$CMAKE_BUILD_FLAGS"
    - mkdir -p build
    - cd build
    - cmake $CMAKE_BUILD_FLAGS ..
    - cmake --build . -- -j$(nproc)
    - cd ..
    - echo "========================================= script (2)"
notifications:
    email:
        recipients:
            - sergiy@skalelabs.com
        on_success: change
        on_failure: always
