language: cpp
sudo: required
cache:
    ccache: true
    directories:
        - $TRAVIS_BUILD_DIR/build/deps
        - $TRAVIS_BUILD_DIR/deps
matrix:
    include:
        - os: linux
          env:
            - PYTHON=3.6
            - BUILDING_FOR_OS=linux
            - CMAKE_BUILD_FLAGS="-DCOVERAGE=ON"
            - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
            - CPU_COUNT=$(nproc)
            - NIGHTLY_BUILD_FLAGS="valgrind --leak-check=yes"
          addons:
              snaps:
                  - valgrind --classic
              apt:
                  packages:
                      - g++-7
                      - clang-format-6.0
                      - gawk
                      - sed
                      - shtool
                      - libffi-dev
                      - libprocps4-dev
                      - yasm
                      - texinfo
                      - flex
                      - bison
                      - libc6-dbg:i386
                      - libc6-dbg
                      - python3.6
                      - python3.6-dev
                  sources: &sources
                      - deadsnakes
                      - ubuntu-toolchain-r-test
          before_script:
              - echo "========================================= before_script (coverage)"
              - sudo apt-get update -qq
              - sudo python -m pip install --upgrade pip
              - sudo python -m pip install pyopenssl ndg-httpsclient pyasn1
              - sudo python -m pip install requests[security]
              - sudo python -m pip install codecov --ignore-installed
              - sudo apt-get install python3.6
              - sudo apt-get install python3-pip
              - sudo apt-get install python3-setuptools
              - python3.6 -m pip install coincurve
              - echo "========================================= before_script (codecov installed)"
              - mkdir -p build
              - cd build
              - cd ..
          after_success:
              - cd python
              - echo "========================================= after_success (dkg-python test)"
              - ./setup.sh || travis terminate 1
              - ./test.sh || travis terminate 1
              - cd ..
              - cd build
              - echo "========================================= after_success (coverage)"
              - if [ $TRAVIS_EVENT_TYPE = "cron" ]; then $NIGHTLY_BUILD_FLAGS ./bls_unit_test || travis_terminate 1; else ./bls_unit_test || travis_terminate 1; fi
              - if [ $TRAVIS_EVENT_TYPE = "cron" ]; then $NIGHTLY_BUILD_FLAGS ./dkg_unit_test || travis_terminate 1; else ./dkg_unit_test || travis_terminate 1; fi
              - if [ $TRAVIS_EVENT_TYPE = "cron" ]; then $NIGHTLY_BUILD_FLAGS ./bls_test || travis_terminate 1; else ./bls_test || travis_terminate 1; fi
              - if [ $TRAVIS_EVENT_TYPE = "cron" ]; then $NIGHTLY_BUILD_FLAGS ./threshold_encryption/te_unit_test || travis_terminate 1; else ./threshold_encryption/te_unit_test || travis_terminate 1; fi
              - if [ $TRAVIS_EVENT_TYPE = "cron" ]; then $NIGHTLY_BUILD_FLAGS ./threshold_encryption/te_test || travis_terminate 1; else ./threshold_encryption/te_test || travis_terminate 1; fi
              - if [ $TRAVIS_EVENT_TYPE = "cron" ]; then $NIGHTLY_BUILD_FLAGS ./threshold_encryption/dkg_te_unit_test || travis_terminate 1; else ./threshold_encryption/dkg_te_unit_test || travis_terminate 1; fi
              - cd ..
              - ./get_code_cov
              - echo "========================================= after_success (coverage gathered to gcov files)"
              - codecov
              - bash <(curl -s https://codecov.io/bash)
              - echo "========================================= after_success (coverage end)"
        - os: osx
          osx_image: xcode10.1
          env:
            - BUILDING_FOR_OS=osx
            - CMAKE_BUILD_FLAGS="-DWITH_PROCPS=OFF"
            - OPENSSL_ROOT_DIR=/usr/local/opt/openssl
            - LIBTOOL=glibtool
            - CPU_COUNT=$(sysctl -n hw.physicalcpu )
          addons:
              apt:
                  packages:
                      - yasm
                      - texinfo
                      - shtool
                      - libtool
          before_script:
              - ln -s $(which glibtool) /usr/local/bin/libtool || true
              - ln -s $(which glibtoolize) /usr/local/bin/libtoolize || true
before_install:
    - eval "${MATRIX_EVAL}"
script:
    - echo "========================================= script (1)"
    - echo "CMAKE_BUILD_FLAGS=$CMAKE_BUILD_FLAGS"
    - cd deps
    - sh -c "while :; do clear; date; sleep 300; done" &
    - ./build.sh PARALLEL_COUNT=$CPU_COUNT &> ./log_of_deps_build.txt || (cat ./log_of_deps_build.txt && travis_terminate 1)
    - cd ..
    - mkdir -p build
    - cd build
    - cmake $CMAKE_BUILD_FLAGS ..
    - if [ "$TRAVIS_OS_NAME" != "osx" ]; then make bls-format-check || travis_terminate 1; fi
    - cmake --build . -- -j$CPU_COUNT
    - cd ..
    - echo "========================================= script (2)"
notifications:
    email:
        recipients:
            - oleg@skalelabs.com
        on_success: change
        on_failure: always
