name: "cla"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]

jobs:
  cla:
    runs-on: ubuntu-latest
    steps:
      - name: "Get Team Members"
        id: team
        # github-script, v6.1.0
        uses: actions/github-script@7a5c598405937d486b0331594b5da2b14db670da
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          result-encoding: string
          script: |
            const members = await github.paginate(
              github.rest.orgs.listMembers,
              { org: "skalenetwork" },
            );
            return members.map(m => m.login).join(",");
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        # Beta Release, v2.1.3-beta
        uses: cla-assistant/github-action@ba066dbae3769e2ce93ec8cfc4fdc51b9db628ba
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN : ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          path-to-signatures: 'signatures/version1/cla.json'
          path-to-document: 'https://skale.space/cla-txt'
          remote-organization-name: 'skalenetwork'
          remote-repository-name: cla-sigs
          allowlist: '${{ steps.team.outputs.result }},*[bot]'
